 export const userData = [
    {
        name: "Jan",
        "Active User": 4000,
      },
      {
        name: "Feb",
        "Active User": 3000,
      },
      {
        name: "Mar",
        "Active User": 5000,
      },
      {
        name: "Apr",
        "Active User": 4000,
      },
      {
        name: "May",
        "Active User": 3000,
      },
      {
        name: "Jun",
        "Active User": 2000,
      },
      {
        name: "Jul",
        "Active User": 4000,
      },
      {
        name: "Agu",
        "Active User": 3000,
      },
      {
        name: "Sep",
        "Active User": 4000,
      },
      {
        name: "Oct",
        "Active User": 1000,
      },
      {
        name: "Nov",
        "Active User": 4000,
      },
      {
        name: "Dec",
        "Active User": 3000,
      },
  
  ];

  export const userRows = [
    { id: 1, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 2, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 3, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 4, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 5, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 6, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 7, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 8, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 9, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
    { id: 10, 
      username: 'Snow Jon',
      email: 'Jon@gmail.com',
      avatar: "https://images.pexels.com/photos/3992656/pexels-photo-3992656.png?auto=compress&cs=tinysrgb&dpr=2&w=500",
      status:"active",
      transaction: "$120.00",
     },
   
];
export const productData = [
  {
    name: "Jan",
    "Sales": 4000,
  },
  {
    name: "Feb",
    "Sales": 3000,
  },
  {
    name: "Mar",
    "Sales": 5000,
  },
];


export const productRows = [
  { id: 1, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 2, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 3, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 4, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 6, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 7, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 8, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 9, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  { id: 10, 
    name: 'Apple Airpods',
    stock: 123,
    img: "https://images.pexels.com/photos/7156886/pexels-photo-7156886.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500",
    status:"active",
    price: "$120.00",
   },
  
 
];